name: Pylint

on:
- push
- pull_request

jobs:
  lint-ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Analysing the code with ruff
      run: |
        pip install -r test-requirements.txt
        ruff format --check
