name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install -y podman
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
    - name: Test with unittest
      run: |
        coverage run --source podman_compose -m unittest pytests/*.py
        python -m unittest tests/*.py
        coverage combine
        coverage report
      env:
        TESTS_DEBUG: 1
